trigger:
- main

jobs:
- job: Build_SDK
  displayName: Build SDK
  pool:
    vmImage: ubuntu-latest
  variables:
    BuildConfiguration: 'Release'
    BuildPlatform: 'any cpu'
  steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1 libssl-dev
      displayName: 'Install libssl dependencies'
    - task: NuGetToolInstaller@1
      displayName: Install NuGet 6.x
      inputs:
        versionSpec: '6.x'
        checkLatest: true
    - task: UseDotNet@2
      displayName: Use .NET 6.0.x
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
    - task: DotNetCoreCLI@2
      displayName: Restore Solution
      inputs:
        command: 'restore'
        projects: 'src/sdk/Microsoft.UnifiedRedisPlatform.SDK.sln'
    - task: DotNetCoreCLI@2
      displayName: Build Library Projects
      inputs:
        command: 'build'
        projects: 'src/sdk/**/*.csproj'

- job: Build_Service
  displayName: Build Service
  pool:
    vmImage: ubuntu-latest
  variables:
    BuildConfiguration: 'Release'
    BuildPlatform: 'any cpu'
  steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1 libssl-dev
      displayName: 'Install libssl dependencies'
    - task: NuGetToolInstaller@1
      displayName: Install NuGet 6.x
      inputs:
        versionSpec: '6.x'
        checkLatest: true
    - task: UseDotNet@2
      displayName: Use .NET 6.0.x
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
    - task: DotNetCoreCLI@2
      displayName: Restore Solution
      inputs:
        command: 'restore'
        projects: 'src/service/Microsoft.UnifiedRedisPlatform.Service/Microsoft.UnifiedRedisPlatform.Service.sln'
    - task: DotNetCoreCLI@2
      displayName: Build Library Projects
      inputs:
        command: 'build'
        projects: 'src/service/**/*.csproj'
  