trigger:
- main

jobs:
- job: Build_SDK
  displayName: Build SDK
  pool:
    vmImage: ubuntu-latest
  variables:
    BuildConfiguration: 'Release'
    BuildPlatform: 'any cpu'
  steps:
    - task: NuGetToolInstaller@1
      displayName: Install NuGet 5.5.0
      inputs:
        versionSpec: '5.5.0'
        checkLatest: true
    - task: UseDotNet@2
      displayName: Use .NET Core 5.0.x
      inputs:
        packageType: 'sdk'
        version: '5.0.x'
    - task: NuGetCommand@2
      displayName: Restore Solution
      inputs:
        command: 'restore'
        restoreSolution: 'src/sdk/Microsoft.UnifiedRedisPlatform.SDK.sln'
    - task: DotNetCoreCLI@2
      displayName: Build Library Projects
      inputs:
        command: 'build'
        projects: 'src/sdk/**/*.csproj'

- job: Build_Service
  displayName: Build Service
  pool:
    vmImage: ubuntu-latest
    variables:
    BuildConfiguration: 'Release'
    BuildPlatform: 'any cpu'
  steps:
    - task: NuGetToolInstaller@1
      displayName: Install NuGet 5.5.0
      inputs:
        versionSpec: '5.5.0'
        checkLatest: true
    - task: UseDotNet@2
      displayName: Use .NET Core 3.1.x
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    - task: NuGetCommand@2
      displayName: Restore Solution
      inputs:
        command: 'restore'
        restoreSolution: 'src/service/Microsoft.UnifiedRedisPlatform.Service/Microsoft.UnifiedRedisPlatform.Service.sln'
    - task: DotNetCoreCLI@2
      displayName: Build Library Projects
      inputs:
        command: 'build'
        projects: 'src/service/**/*.csproj'
  