<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Microsoft.UnifiedRedisPlatform.LocalTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\service\Microsoft.UnifiedRedisPlatform.Service\Infrastructure\Redis\Microsoft.UnifiedPlatform.Service.Redis.csproj" />
    <ProjectReference Include="..\..\..\sdk\Core\Microsoft.UnifiedRedisPlatform.Core.csproj" />
  </ItemGroup>

</Project>
