name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-code-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/sdk/Microsoft.UnifiedRedisPlatform.SDK.sln
    - name: Build
      run: dotnet build src/sdk/Microsoft.UnifiedRedisPlatform.SDK.sln --no-restore
    - name: Test
      run: dotnet test src/sdk/Microsoft.UnifiedRedisPlatform.SDK.sln --no-build --verbosity normal
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/tests/Microsoft.UnifiedRedisPlatform.TestApps/Microsoft.UnifiedRedisPlatform.Tests.sln
    - name: Build
      run: dotnet build src/tests/Microsoft.UnifiedRedisPlatform.TestApps/Microsoft.UnifiedRedisPlatform.Tests.sln --no-restore
    - name: Test
      run: dotnet test src/tests/Microsoft.UnifiedRedisPlatform.TestApps/Microsoft.UnifiedRedisPlatform.Tests.sln --no-build --verbosity normal
